name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: List and Read File
      run: |
        echo "My First Github Actions Job"
        run: ls -ltr
        run: cat README.md
    - name: Generate ASCII Artwork
      run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

    # - name: Read File
    #  run: cat README.md
